name: Weekly Exercise 2 Test

on:
  push:
    branches: [master, main]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: List Directory
        run: |
          ls
          cd app
          cd build
          cd reports
          cd androidTests
          cd connected